name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: src/

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Setup imports
      uses: Jerome1337/goimports-action@v1.0.2
      with:
        goimports-path: './src'

    - name: Build
      run: go build -v ./...
      env:
        GOPATH: /home/runner/work/Lux/Lux
          
    - name: Test
      run: go test -v ./...
