on: push
jobs:
  deployment:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.2.2
    - run: curl -s 'https://bandev.uk/api/lux/commands.json' | \ $pythonLocation/python -c "import sys, json; print(json.load(sys.stdin)['commands'][0]['name'])"
      
