on: push
jobs:
  deployment:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.2.2
    - run: pip install requests
    - run: python3 scripts/update-readme.py
      
