on: push
jobs:
  deployment:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
    - name: Update Readme
      run: curl -s 'https://bandev.uk/api/lux/commands.json' | \ python -c "import sys, json; print(json.load(sys.stdin)['commands'][0]['name'])"
      
