name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@latest
        with:
          identifier: JackDevey.Lux
          installers-regex: '\.exe$'
          delete-previous-version: 'true'
          token: ${{ secrets.WINGET_TOKEN }}
